export const colleges = [
  {
    id: 1,
    name: "Indian Institute of Technology Delhi",
    location: "New Delhi",
    district: "New Delhi",
    state: "Delhi",
    type: "Government",
    category: "IIT",
    established: 1961,
    ranking: 1,
    image: "/iit-delhi-campus-modern-architecture.jpg",
    description: "One of India's premier engineering institutions with world-class facilities and faculty.",
    courses: ["Computer Science", "Mechanical Engineering", "Civil Engineering", "Electrical Engineering"],
    coursesDetails: [
      { name: "B.Tech Computer Science", level: "UG", duration: "4 years", eligibility: "12th + JEE Advanced", avgSalary: "25 LPA", seats: 120 },
      { name: "B.Tech Mechanical Engineering", level: "UG", duration: "4 years", eligibility: "12th + JEE Advanced", avgSalary: "18 LPA", seats: 100 },
    ],
    cutoff: "99.5%ile",
    placements: "98%",
    avgFees: "900000",
    admissionProcess: "JEE Advanced Merit",
    entranceExam: "JEE Advanced",
    stream: "Science",
    facilities: ["Library", "Labs", "Hostels", "Sports Complex", "Cafeteria"],
    accreditation: "NAAC A++",
  },
  {
    id: 2,
    name: "National Institute of Technology Calicut",
    location: "Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    type: "Government",
    category: "NIT",
    established: 1961,
    ranking: 25,
    image: "/nit-calicut-campus-green-landscape.jpg",
    description: "A leading engineering college in Kerala with excellent academic and research programs.",
    courses: ["Electronics", "Computer Science", "Mechanical Engineering", "Chemical Engineering"],
    coursesDetails: [
      { name: "B.Tech Computer Science", level: "UG", duration: "4 years", eligibility: "12th + JEE Advanced", avgSalary: "18 LPA", seats: 80 },
      { name: "B.Tech Electronics", level: "UG", duration: "4 years", eligibility: "12th + JEE Advanced", avgSalary: "15 LPA", seats: 60 },
    ],
    cutoff: "95%ile",
    placements: "95%",
    avgFees: "650000",
    admissionProcess: "JEE Advanced Merit",
    entranceExam: "JEE Advanced",
    stream: "Science",
    facilities: ["Library", "Labs", "Hostels", "Sports Complex", "Cafeteria", "Medical Center"],
    accreditation: "NAAC A",
  },
  {
    id: 3,
    name: "University of Kerala",
    location: "Thiruvananthapuram",
    district: "Thiruvananthapuram",
    state: "Kerala",
    type: "Government",
    category: "University",
    established: 1957,
    ranking: 45,
    image: "/university-of-kerala-historic-building.jpg",
    description: "The oldest university in Kerala offering diverse undergraduate and postgraduate programs.",
    courses: ["Arts", "Science", "Commerce", "Law"],
    coursesDetails: [
      { name: "BA English", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "6 LPA", seats: 200 },
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "8 LPA", seats: 150 },
    ],
    cutoff: "75%ile",
    placements: "80%",
    avgFees: "350000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Hostels", "Cafeteria"],
    accreditation: "NAAC B+",
  },
  {
    id: 4,
    name: "Cochin University of Science and Technology",
    location: "Kochi",
    district: "Ernakulam",
    state: "Kerala",
    type: "Government",
    category: "University",
    established: 1971,
    ranking: 55,
    image: "/cusat-campus-waterfront.jpg",
    description: "Known for science and technology programs with research facilities.",
    courses: ["Engineering", "Science", "Technology", "Management"],
    coursesDetails: [
      { name: "BTech Computer Science", level: "UG", duration: "4 years", eligibility: "12th + CUSAT", avgSalary: "12 LPA", seats: 100 },
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "7 LPA", seats: 80 },
    ],
    cutoff: "80%ile",
    placements: "85%",
    avgFees: "450000",
    admissionProcess: "CUSAT CAT",
    entranceExam: "CUSAT CAT",
    stream: "Science",
    facilities: ["Library", "Labs", "Hostels", "Sports", "Cafeteria", "Medical"],
    accreditation: "NAAC A",
  },
  {
    id: 5,
    name: "Rajagiri College of Social Sciences",
    location: "Kochi",
    district: "Ernakulam",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1928,
    ranking: 75,
    image: "/rajagiri-college-campus-kerala.jpg",
    description: "Premier institution for social sciences and humanities education.",
    courses: ["Psychology", "Economics", "Sociology", "Media Studies"],
    coursesDetails: [
      { name: "BA Psychology", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 60 },
      { name: "MA Economics", level: "PG", duration: "2 years", eligibility: "BA Graduate", avgSalary: "9 LPA", seats: 40 },
    ],
    cutoff: "85%ile",
    placements: "82%",
    avgFees: "350000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Commerce,Arts",
    facilities: ["Library", "Labs", "Cafeteria", "Sports", "Counseling"],
    accreditation: "NAAC A+",
  },
  {
    id: 6,
    name: "Mar Ivanios College",
    location: "Thiruvananthapuram",
    district: "Thiruvananthapuram",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1967,
    ranking: 88,
    image: "/mar-ivanios-college-kerala.jpg",
    description: "Excellence in science education with strong industry connections.",
    courses: ["Physics", "Chemistry", "Biology", "Mathematics"],
    coursesDetails: [
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "7 LPA", seats: 70 },
      { name: "B.Sc Chemistry", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 70 },
    ],
    cutoff: "88%ile",
    placements: "80%",
    avgFees: "300000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science",
    facilities: ["Library", "Labs", "Hostel", "Cafeteria", "Sports"],
    accreditation: "NAAC B+",
  },
  {
    id: 7,
    name: "Maharaja's College",
    location: "Thiruvananthapuram",
    district: "Thiruvananthapuram",
    state: "Kerala",
    type: "Government",
    category: "Autonomous",
    established: 1864,
    ranking: 65,
    image: "/mar-ivanios-college-kerala.jpg",
    description: "One of Kerala's oldest colleges with strong academic tradition.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA History", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "4.5 LPA", seats: 100 },
      { name: "B.Com Accounting", level: "UG", duration: "3 years", eligibility: "12th Commerce", avgSalary: "5.5 LPA", seats: 80 },
    ],
    cutoff: "80%ile",
    placements: "78%",
    avgFees: "200000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Arts,Commerce",
    facilities: ["Library", "Labs", "Cafeteria", "Hostel"],
    accreditation: "NAAC A",
  },
  {
    id: 8,
    name: "Sree Narayana College",
    location: "Kollam",
    district: "Kollam",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1946,
    ranking: 82,
    image: "/rajagiri-college-campus-kerala.jpg",
    description: "Quality education in arts, science and commerce streams.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA English", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 90 },
      { name: "B.Sc Botany", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 70 },
    ],
    cutoff: "78%ile",
    placements: "75%",
    avgFees: "280000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Cafeteria", "Sports"],
    accreditation: "NAAC B+",
  },
  {
    id: 9,
    name: "Pushpagiri College",
    location: "Pathanamthitta",
    district: "Pathanamthitta",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1989,
    ranking: 85,
    image: "/nit-calicut-campus-green-landscape.jpg",
    description: "Comprehensive higher education institution with modern infrastructure.",
    courses: ["Science", "Commerce", "Humanities"],
    coursesDetails: [
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 80 },
      { name: "BBA", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "7 LPA", seats: 60 },
    ],
    cutoff: "76%ile",
    placements: "80%",
    avgFees: "320000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Commerce",
    facilities: ["Library", "Labs", "Cafeteria", "Hostel", "Medical Center"],
    accreditation: "NAAC B+",
  },
  {
    id: 10,
    name: "Prabhat Arts and Science College",
    location: "Alappuzha",
    district: "Alappuzha",
    state: "Kerala",
    type: "Private",
    category: "Aided",
    established: 1988,
    ranking: 90,
    image: "/cusat-campus-waterfront.jpg",
    description: "Quality education with focus on student development.",
    courses: ["Science", "Commerce", "Humanities"],
    coursesDetails: [
      { name: "B.Com Finance", level: "UG", duration: "3 years", eligibility: "12th Commerce", avgSalary: "5.5 LPA", seats: 85 },
      { name: "B.Sc Mathematics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 70 },
    ],
    cutoff: "74%ile",
    placements: "72%",
    avgFees: "250000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Commerce",
    facilities: ["Library", "Labs", "Cafeteria"],
    accreditation: "NAAC B",
  },
  {
    id: 11,
    name: "St. Thomas College",
    location: "Kottayam",
    district: "Kottayam",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1925,
    ranking: 60,
    image: "/rajagiri-college-campus-kerala.jpg",
    description: "Premier institution offering comprehensive educational programs.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA Economics", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "6 LPA", seats: 100 },
      { name: "B.Sc Chemistry", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 80 },
    ],
    cutoff: "82%ile",
    placements: "84%",
    avgFees: "400000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Hostels", "Sports", "Cafeteria"],
    accreditation: "NAAC A",
  },
  {
    id: 12,
    name: "Christ College",
    location: "Irinjalakuda",
    district: "Thrissur",
    state: "Kerala",
    type: "Private",
    category: "Autonomous",
    established: 1976,
    ranking: 70,
    image: "/nit-calicut-campus-green-landscape.jpg",
    description: "Excellence in arts, science and professional education.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA Political Science", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 90 },
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "7 LPA", seats: 75 },
    ],
    cutoff: "81%ile",
    placements: "82%",
    avgFees: "350000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Sports Complex", "Cafeteria"],
    accreditation: "NAAC B+",
  },
  {
    id: 13,
    name: "Govt College for Women",
    location: "Thiruvananthapuram",
    district: "Thiruvananthapuram",
    state: "Kerala",
    type: "Government",
    category: "Aided",
    established: 1919,
    ranking: 72,
    image: "/mar-ivanios-college-kerala.jpg",
    description: "Premium education for women with strong women empowerment focus.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA English", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5.5 LPA", seats: 120 },
      { name: "B.Sc Zoology", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 100 },
    ],
    cutoff: "79%ile",
    placements: "80%",
    avgFees: "180000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Hostel", "Sports", "Health Center"],
    accreditation: "NAAC B+",
  },
  {
    id: 14,
    name: "Calicut College",
    location: "Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    type: "Government",
    category: "Aided",
    established: 1817,
    ranking: 68,
    image: "/cusat-campus-waterfront.jpg",
    description: "One of Kerala's oldest colleges with rich academic heritage.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA Malayalam", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "4.5 LPA", seats: 110 },
      { name: "B.Sc Zoology", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 85 },
    ],
    cutoff: "77%ile",
    placements: "76%",
    avgFees: "220000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Cafeteria", "Sports"],
    accreditation: "NAAC B",
  },
  {
    id: 15,
    name: "Govt Victoria College",
    location: "Palakkad",
    district: "Palakkad",
    state: "Kerala",
    type: "Government",
    category: "Aided",
    established: 1871,
    ranking: 73,
    image: "/rajagiri-college-campus-kerala.jpg",
    description: "Premier government college with comprehensive academic offerings.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA Philosophy", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 100 },
      { name: "B.Sc Mathematics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 80 },
    ],
    cutoff: "78%ile",
    placements: "78%",
    avgFees: "200000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Hostel", "Cafeteria"],
    accreditation: "NAAC B+",
  },
  {
    id: 16,
    name: "Malabar College",
    location: "Kozhikode",
    district: "Kozhikode",
    state: "Kerala",
    type: "Private",
    category: "Aided",
    established: 1927,
    ranking: 76,
    image: "/nit-calicut-campus-green-landscape.jpg",
    description: "Quality education with emphasis on holistic student development.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA Communication", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5.5 LPA", seats: 95 },
      { name: "B.Sc Physics", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 75 },
    ],
    cutoff: "79%ile",
    placements: "79%",
    avgFees: "280000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Sports", "Cafeteria", "Hostel"],
    accreditation: "NAAC B+",
  },
  {
    id: 17,
    name: "Sree Sankaracharya University",
    location: "Kaladi",
    district: "Ernakulam",
    state: "Kerala",
    type: "Private",
    category: "University",
    established: 2009,
    ranking: 80,
    image: "/cusat-campus-waterfront.jpg",
    description: "University with focus on Indian culture and modern education.",
    courses: ["Arts", "Science", "Management"],
    coursesDetails: [
      { name: "BA Sanskrit", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 60 },
      { name: "B.Sc Environmental Science", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 50 },
    ],
    cutoff: "75%ile",
    placements: "74%",
    avgFees: "320000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts",
    facilities: ["Library", "Labs", "Hostel", "Cafeteria", "Temple"],
    accreditation: "NAAC B",
  },
  {
    id: 18,
    name: "Malappuram College of Engineering",
    location: "Malappuram",
    district: "Malappuram",
    state: "Kerala",
    type: "Private",
    category: "Engineering",
    established: 2006,
    ranking: 95,
    image: "/nit-calicut-campus-green-landscape.jpg",
    description: "Modern engineering college with state-of-the-art facilities.",
    courses: ["Computer Science", "Mechanical", "Electrical", "Civil"],
    coursesDetails: [
      { name: "B.Tech CS", level: "UG", duration: "4 years", eligibility: "12th + KEAM", avgSalary: "10 LPA", seats: 60 },
      { name: "B.Tech Mechanical", level: "UG", duration: "4 years", eligibility: "12th + KEAM", avgSalary: "8 LPA", seats: 50 },
    ],
    cutoff: "70%ile",
    placements: "85%",
    avgFees: "600000",
    admissionProcess: "KEAM Merit",
    entranceExam: "KEAM",
    stream: "Science",
    facilities: ["Labs", "Hostel", "Sports", "Cafeteria", "Library"],
    accreditation: "NAAC B",
  },
  {
    id: 19,
    name: "Kannur University",
    location: "Kannur",
    district: "Kannur",
    state: "Kerala",
    type: "Government",
    category: "University",
    established: 1996,
    ranking: 67,
    image: "/rajagiri-college-campus-kerala.jpg",
    description: "Central university with multiple affiliated colleges across North Kerala.",
    courses: ["Arts", "Science", "Commerce"],
    coursesDetails: [
      { name: "BA History", level: "UG", duration: "3 years", eligibility: "12th Pass", avgSalary: "5 LPA", seats: 150 },
      { name: "B.Sc Chemistry", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6.5 LPA", seats: 120 },
    ],
    cutoff: "77%ile",
    placements: "76%",
    avgFees: "250000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Arts,Commerce",
    facilities: ["Library", "Labs", "Hostel", "Cafeteria", "Sports"],
    accreditation: "NAAC B+",
  },
  {
    id: 20,
    name: "Wayanad University",
    location: "Kalpetta",
    district: "Wayanad",
    state: "Kerala",
    type: "Government",
    category: "University",
    established: 2006,
    ranking: 92,
    image: "/cusat-campus-waterfront.jpg",
    description: "University in scenic Western Ghats with focus on sustainable development.",
    courses: ["Science", "Commerce", "Humanities"],
    coursesDetails: [
      { name: "B.Sc Ecology", level: "UG", duration: "3 years", eligibility: "12th Science", avgSalary: "6 LPA", seats: 80 },
      { name: "B.Com Management", level: "UG", duration: "3 years", eligibility: "12th Commerce", avgSalary: "5.5 LPA", seats: 70 },
    ],
    cutoff: "72%ile",
    placements: "70%",
    avgFees: "300000",
    admissionProcess: "Merit Based",
    entranceExam: "None",
    stream: "Science,Commerce",
    facilities: ["Library", "Labs", "Hostel", "Cafeteria", "Sports"],
    accreditation: "NAAC B",
  },
]

export const districts = [
  "Thiruvananthapuram", "Kollam", "Pathanamthitta", "Alappuzha",
  "Kottayam", "Idukki", "Ernakulam", "Thrissur", "Palakkad",
  "Malappuram", "Kozhikode", "Wayanad", "Kannur", "Kasaragod"
]

export const streams = ["Science", "Commerce", "Arts"]
export const levels = ["UG", "PG", "Diploma"]
export const collegeTypes = ["Government", "Private"]
export const feeRanges = [
  { min: 0, max: 300000, label: "Up to 3 Lakhs" },
  { min: 300000, max: 600000, label: "3 - 6 Lakhs" },
  { min: 600000, max: 1000000, label: "6 - 10 Lakhs" },
  { min: 1000000, max: 2000000, label: "Above 10 Lakhs" },
]

export const courseCategories = [
  "Engineering & Technology",
  "Medical & Health Sciences",
  "Commerce & Business",
  "Arts & Humanities",
  "Science",
  "Law",
  "Design & Media",
  "Computer & IT",
  "Management (MBA)"
]

export const courses = [
  {
    id: 1,
    name: "B.Tech Computer Science",
    category: "Engineering & Technology",
    duration: "4 years",
    eligibility: "12th Science + JEE Mains",
    entranceExam: "JEE Mains",
    careerScope: "Software Engineer, Web Developer, Data Scientist, AI/ML Engineer",
    avgSalary: "12-25 LPA",
    description: "Comprehensive engineering program focusing on computer systems, programming, and software development.",
    topColleges: ["IIT Delhi", "NIT Calicut", "CUSAT"],
    futureScope: "High demand in tech industry with continuous growth in emerging technologies."
  },
  {
    id: 2,
    name: "MBBS",
    category: "Medical & Health Sciences",
    duration: "5.5 years",
    eligibility: "12th Science (PCB)",
    entranceExam: "NEET",
    careerScope: "Doctor, Surgeon, Medical Practitioner, Specialist",
    avgSalary: "8-15 LPA",
    description: "Medical degree program leading to professional practice as a physician.",
    topColleges: ["Government Medical College"],
    futureScope: "Always in demand with secure government and private sector opportunities."
  },
  {
    id: 3,
    name: "BBA",
    category: "Commerce & Business",
    duration: "3 years",
    eligibility: "12th Pass",
    entranceExam: "None",
    careerScope: "Business Manager, HR Officer, Finance Manager, Entrepreneur",
    avgSalary: "6-12 LPA",
    description: "Business administration program covering management, finance, and entrepreneurship.",
    topColleges: ["Rajagiri College", "St. Thomas College"],
    futureScope: "Growing opportunities in startups, consulting, and corporate sectors."
  },
  {
    id: 4,
    name: "B.Com",
    category: "Commerce & Business",
    duration: "3 years",
    eligibility: "12th Pass",
    entranceExam: "None",
    careerScope: "Accountant, Financial Analyst, Tax Consultant, Auditor",
    avgSalary: "5-10 LPA",
    description: "Commerce degree with focus on accounting, finance, and business studies.",
    topColleges: ["University of Kerala", "Mar Ivanios College"],
    futureScope: "Essential qualification for finance and accounting careers."
  },
  {
    id: 5,
    name: "BCA",
    category: "Computer & IT",
    duration: "3 years",
    eligibility: "12th Pass",
    entranceExam: "None",
    careerScope: "Software Developer, Web Developer, IT Support, Database Administrator",
    avgSalary: "6-14 LPA",
    description: "Computer application program for IT professionals with programming focus.",
    topColleges: ["CUSAT", "NIT Calicut"],
    futureScope: "Strong demand in IT industry with diverse career options."
  },
  {
    id: 6,
    name: "BA English",
    category: "Arts & Humanities",
    duration: "3 years",
    eligibility: "12th Pass",
    entranceExam: "None",
    careerScope: "Journalist, Content Writer, Teacher, Publishing Professional",
    avgSalary: "4-8 LPA",
    description: "English literature and language studies with communication skills.",
    topColleges: ["University of Kerala", "Maharaja's College"],
    futureScope: "Growing opportunities in media, education, and content creation."
  },
  {
    id: 7,
    name: "B.Sc Physics",
    category: "Science",
    duration: "3 years",
    eligibility: "12th Science",
    entranceExam: "None",
    careerScope: "Physicist, Researcher, Engineer, Teacher, Lab Technician",
    avgSalary: "6-10 LPA",
    description: "Science program focusing on physics fundamentals and research.",
    topColleges: ["Mar Ivanios College", "University of Kerala"],
    futureScope: "Essential for research and advanced studies in science and engineering."
  },
  {
    id: 8,
    name: "B.Sc Nursing",
    category: "Medical & Health Sciences",
    duration: "4 years",
    eligibility: "12th Science (PCB)",
    entranceExam: "NEET / CUCET",
    careerScope: "Nurse, Hospital Administrator, Health Educator, Research Nurse",
    avgSalary: "4-8 LPA",
    description: "Professional nursing program for healthcare delivery.",
    topColleges: ["Government Medical College"],
    futureScope: "High demand in healthcare sector with global opportunities."
  },
  {
    id: 9,
    name: "LLB",
    category: "Law",
    duration: "3 years",
    eligibility: "12th Pass / BA Degree",
    entranceExam: "CLAT / LSAT",
    careerScope: "Lawyer, Judge, Legal Consultant, Corporate Counsel",
    avgSalary: "8-20 LPA",
    description: "Law degree for legal practice and judicial careers.",
    topColleges: ["University of Kerala", "Government Law College"],
    futureScope: "Diverse opportunities in legal practice, judiciary, and corporate sectors."
  },
  {
    id: 10,
    name: "B.Des",
    category: "Design & Media",
    duration: "4 years",
    eligibility: "12th Pass",
    entranceExam: "Design Entrance Test",
    careerScope: "Graphic Designer, UI/UX Designer, Product Designer, Design Director",
    avgSalary: "6-15 LPA",
    description: "Design program combining creativity with technical skills.",
    topColleges: ["CUSAT", "NIT Calicut"],
    futureScope: "Expanding field with opportunities in tech, media, and creative industries."
  },
  {
    id: 11,
    name: "MBA",
    category: "Management (MBA)",
    duration: "2 years",
    eligibility: "Bachelor's Degree + Work Experience",
    entranceExam: "CAT / XAT / GMAT",
    careerScope: "Business Manager, Consultant, Executive, Entrepreneur",
    avgSalary: "15-40 LPA",
    description: "Master's program in business administration for career advancement.",
    topColleges: ["CUSAT", "Rajagiri College"],
    futureScope: "Critical for leadership and management roles in global organizations."
  },
  {
    id: 12,
    name: "Hotel Management",
    category: "Management (MBA)",
    duration: "3 years",
    eligibility: "12th Pass",
    entranceExam: "None",
    careerScope: "Hotel Manager, Chef, Event Organizer, Travel Consultant",
    avgSalary: "5-12 LPA",
    description: "Hospitality management program for tourism and hospitality industry.",
    topColleges: ["Institute of Hotel Management"],
    futureScope: "Booming industry with international opportunities and career growth."
  }
]

export const collegeDetails = {
  1: {
    ...colleges[0],
    fullDescription:
      "Indian Institute of Technology Delhi is one of the premier engineering institutions in India, established in 1961. It offers world-class education in engineering and technology with state-of-the-art laboratories and experienced faculty.",
    departments: [
      { name: "Computer Science & Engineering", seats: 120, cutoff: "99.5%ile" },
      { name: "Mechanical Engineering", seats: 100, cutoff: "99.2%ile" },
      { name: "Civil Engineering", seats: 80, cutoff: "98.8%ile" },
      { name: "Electrical Engineering", seats: 90, cutoff: "99.1%ile" },
    ],
    facilities: ["Library", "Laboratories", "Sports Complex", "Hostel", "Cafeteria", "Health Center"],
    admissionProcess: "Based on JEE Advanced scores. Top qualifying candidates from merit list.",
    applicationDeadline: "June 15, 2024",
  },
}
